### ISSUE TITLE
bitcoin.com crashes on Oreo 8.1 (LineageOS 15.1rc2)

### ISSUE THREAD

**Issue by i-am-user** [Bitcoin-com/Wallet#370]
lineage-15.1-20180925-nightly-klte-signed.zip
bitcoin.com-wallet-5.0-rc2-android-derived.apk
Galaxy S5 (SM-G900F)

LineageOS 14.1 - works fine
upgrade LineageOS 14.1->15.1 - wallet crashes
system/data wipe, clean install LineageOS 15.1, install apk - wallet crashes, but shows splashscreen at least.

**Comment by i-am-user** [comment]
LineageOS 15.1 is based on Oreo 8.1

**Comment by i-am-user** [comment]
rc5 still does not start

**Comment by alfonsofy** [comment]
@i-am-user is this still happening on your LineageOS phone?

**Comment by smacz42** [comment]
I installed the latest, and got the following message:

```
FATAL EXCEPTION: pool-5-thread-1
Process: com.bitcoin.mwallet, PID: 23745
java.lang.SecurityException: Failed to find provider com.google.android.gsf.gservices for user 0; expected to find a valid ContentProvider for this authority
	at android.os.Parcel.createException(Parcel.java:1942)
	at android.os.Parcel.readException(Parcel.java:1910)
	at android.os.Parcel.readException(Parcel.java:1860)
	at android.content.IContentService$Stub$Proxy.registerContentObserver(IContentService.java:779)
	at android.content.ContentResolver.registerContentObserver(ContentResolver.java:1972)
	at android.content.ContentResolver.registerContentObserver(ContentResolver.java:1961)
	at com.google.android.gms.internal.zzdmf.zza(Unknown Source:35)
	at com.google.android.gms.internal.zzdmf.zza(Unknown Source:6)
	at com.google.android.gms.internal.zzewh.zzan(Unknown Source:125)
	at com.google.android.gms.internal.zzewh.<init>(Unknown Source:23)
	at com.google.android.gms.internal.zzevz.zzcke(Unknown Source:138)
	at com.google.android.gms.internal.zzevz.zzb(Unknown Source:0)
	at com.google.android.gms.internal.zzewa.run(Unknown Source:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.content.ContentService.registerContentObserver(ContentService.java:340)
	at android.content.IContentService$Stub.onTransact(IContentService.java:76)
	at com.android.server.content.ContentService.onTransact(ContentService.java:262)
	at android.os.Binder.execTransact(Binder.java:731)
```

Does this wallet now require gapps?!?

**Comment by i-am-user** [comment]
v5.13-rc4 finally again starts fine without gapps, (Lineage 14.1)

thank you
