### ISSUE TITLE
[Linux][Desktop] Failure While Building 4.5.1 (failure in npm run build:desktop)

### ISSUE THREAD

**Issue by JollyMort** [Bitcoin-com/Wallet#66]
Trying to update [AUR package](https://aur.archlinux.org/packages/bitcoin-com/) with new ver., failure in executing `npm run build:desktop` in task `browserify:dist`.

Console log:

```
> bitcoin.com@4.5.1 build:desktop /home/user/aur/bitcoin-com/src/bitcoin-com-4.5.1
> grunt desktop

(node:2125) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
Running "nggettext_compile:all" (nggettext_compile) task

Running "exec:appConfig" (exec) task
v4.5.1 #9fff29b App:Bitcoin.com Wallet

Running "exec:externalServices" (exec) task

Running "browserify:dist" (browserify) task
>> /home/user/aur/bitcoin-com/src/bitcoin-com-4.5.1/www/index.html:1
>> <!doctype html>
>> ^
>> ParseError: Unexpected token
Warning: Error running grunt-browserify. Use --force to continue.

Aborted due to warnings.
npm ERR! code ELIFECYCLE
npm ERR! errno 6
npm ERR! bitcoin.com@4.5.1 build:desktop: `grunt desktop`
npm ERR! Exit status 6
npm ERR! 
npm ERR! Failed at the bitcoin.com@4.5.1 build:desktop script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2018-03-05T19_55_23_045Z-debug.log
==> ERROR: A failure occurred in build().
    Aborting...
```

npm debug.log

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build:desktop' ]
2 info using npm@5.7.1
3 info using node@v9.7.1
4 verbose run-script [ 'prebuild:desktop', 'build:desktop', 'postbuild:desktop' ]
5 info lifecycle bitcoin.com@4.5.1~prebuild:desktop: bitcoin.com@4.5.1
6 info lifecycle bitcoin.com@4.5.1~build:desktop: bitcoin.com@4.5.1
7 verbose lifecycle bitcoin.com@4.5.1~build:desktop: unsafe-perm in lifecycle true
8 verbose lifecycle bitcoin.com@4.5.1~build:desktop: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/user/aur/bitcoin-com/src/bitcoin-com-4.5.1/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
9 verbose lifecycle bitcoin.com@4.5.1~build:desktop: CWD: /home/user/aur/bitcoin-com/src/bitcoin-com-4.5.1
10 silly lifecycle bitcoin.com@4.5.1~build:desktop: Args: [ '-c', 'grunt desktop' ]
11 silly lifecycle bitcoin.com@4.5.1~build:desktop: Returned: code: 6  signal: null
12 info lifecycle bitcoin.com@4.5.1~build:desktop: Failed to exec build:desktop script
13 verbose stack Error: bitcoin.com@4.5.1 build:desktop: `grunt desktop`
13 verbose stack Exit status 6
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at EventEmitter.emit (events.js:127:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:127:13)
13 verbose stack     at maybeClose (internal/child_process.js:936:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
14 verbose pkgid bitcoin.com@4.5.1
15 verbose cwd /home/user/aur/bitcoin-com/src/bitcoin-com-4.5.1
16 verbose Linux 4.15.6-1-ARCH
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build:desktop"
18 verbose node v9.7.1
19 verbose npm  v5.7.1
20 error code ELIFECYCLE
21 error errno 6
22 error bitcoin.com@4.5.1 build:desktop: `grunt desktop`
22 error Exit status 6
23 error Failed at the bitcoin.com@4.5.1 build:desktop script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 6, true ]
```

**Comment by JollyMort** [comment]
Weird, I tried 4.5.0 again and I get the same error. Yesterday it worked!
